### ISSUE TITLE
Where did the Pakets go?

### ISSUE THREAD

**Issue by TecCheck** [Xiphoseer/LU-Docs#14]
Hi, I just wondered where the packet and game message documentation went. Did you delete them by accident or is this part of bigger changes?

**Comment by Xiphoseer** [comment]
Yeah, that's an intentional change.

@lcdr has been using https://github.com/lcdr/lu_packets as the main definition for a while and I want to de-duplicate these definitions.

That repo has a generated HTML documentation too and it includes kore details for some packets as well.

**Comment by TecCheck** [comment]
Oh, nice. This is really neat. Thank you :)
